// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/darwinbatres/drawgo/backend/internal/repository (interfaces: UserRepo,RefreshTokenRepo,AccountRepo,AuditRepo,OrgRepo,MembershipRepo,BoardRepo,BoardVersionRepo,BoardPermissionRepo,BoardAssetRepo,ShareLinkRepo,BackupRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/testutil/mocks/mock_repos.go -package=mocks github.com/darwinbatres/drawgo/backend/internal/repository UserRepo,RefreshTokenRepo,AccountRepo,AuditRepo,OrgRepo,MembershipRepo,BoardRepo,BoardVersionRepo,BoardPermissionRepo,BoardAssetRepo,ShareLinkRepo,BackupRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/darwinbatres/drawgo/backend/internal/models"
	repository "github.com/darwinbatres/drawgo/backend/internal/repository"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepo) Create(ctx context.Context, email string, name, passwordHash *string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, email, name, passwordHash)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepoMockRecorder) Create(ctx, email, name, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepo)(nil).Create), ctx, email, name, passwordHash)
}

// CreateOrGetByOAuth mocks base method.
func (m *MockUserRepo) CreateOrGetByOAuth(ctx context.Context, email string, name, image *string, emailVerified bool) (*models.User, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrGetByOAuth", ctx, email, name, image, emailVerified)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateOrGetByOAuth indicates an expected call of CreateOrGetByOAuth.
func (mr *MockUserRepoMockRecorder) CreateOrGetByOAuth(ctx, email, name, image, emailVerified any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrGetByOAuth", reflect.TypeOf((*MockUserRepo)(nil).CreateOrGetByOAuth), ctx, email, name, image, emailVerified)
}

// ExistsByEmail mocks base method.
func (m *MockUserRepo) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockUserRepoMockRecorder) ExistsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockUserRepo)(nil).ExistsByEmail), ctx, email)
}

// GetByEmail mocks base method.
func (m *MockUserRepo) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// UpdateProfile mocks base method.
func (m *MockUserRepo) UpdateProfile(ctx context.Context, id string, name, image *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, id, name, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserRepoMockRecorder) UpdateProfile(ctx, id, name, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserRepo)(nil).UpdateProfile), ctx, id, name, image)
}

// VerifyEmail mocks base method.
func (m *MockUserRepo) VerifyEmail(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockUserRepoMockRecorder) VerifyEmail(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockUserRepo)(nil).VerifyEmail), ctx, id)
}

// MockRefreshTokenRepo is a mock of RefreshTokenRepo interface.
type MockRefreshTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepoMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepoMockRecorder is the mock recorder for MockRefreshTokenRepo.
type MockRefreshTokenRepoMockRecorder struct {
	mock *MockRefreshTokenRepo
}

// NewMockRefreshTokenRepo creates a new mock instance.
func NewMockRefreshTokenRepo(ctrl *gomock.Controller) *MockRefreshTokenRepo {
	mock := &MockRefreshTokenRepo{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepo) EXPECT() *MockRefreshTokenRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenRepo) Create(ctx context.Context, userID, rawToken, userAgent, ip string, expiresAt time.Time) (*models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, rawToken, userAgent, ip, expiresAt)
	ret0, _ := ret[0].(*models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepoMockRecorder) Create(ctx, userID, rawToken, userAgent, ip, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepo)(nil).Create), ctx, userID, rawToken, userAgent, ip, expiresAt)
}

// DeleteExpired mocks base method.
func (m *MockRefreshTokenRepo) DeleteExpired(ctx context.Context, before time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx, before)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockRefreshTokenRepoMockRecorder) DeleteExpired(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockRefreshTokenRepo)(nil).DeleteExpired), ctx, before)
}

// GetByHash mocks base method.
func (m *MockRefreshTokenRepo) GetByHash(ctx context.Context, rawToken string) (*models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", ctx, rawToken)
	ret0, _ := ret[0].(*models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockRefreshTokenRepoMockRecorder) GetByHash(ctx, rawToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockRefreshTokenRepo)(nil).GetByHash), ctx, rawToken)
}

// IsTokenFamilyCompromised mocks base method.
func (m *MockRefreshTokenRepo) IsTokenFamilyCompromised(ctx context.Context, rawToken string) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTokenFamilyCompromised", ctx, rawToken)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IsTokenFamilyCompromised indicates an expected call of IsTokenFamilyCompromised.
func (mr *MockRefreshTokenRepoMockRecorder) IsTokenFamilyCompromised(ctx, rawToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTokenFamilyCompromised", reflect.TypeOf((*MockRefreshTokenRepo)(nil).IsTokenFamilyCompromised), ctx, rawToken)
}

// RevokeAllForUser mocks base method.
func (m *MockRefreshTokenRepo) RevokeAllForUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MockRefreshTokenRepoMockRecorder) RevokeAllForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MockRefreshTokenRepo)(nil).RevokeAllForUser), ctx, userID)
}

// RevokeByID mocks base method.
func (m *MockRefreshTokenRepo) RevokeByID(ctx context.Context, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByID", ctx, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByID indicates an expected call of RevokeByID.
func (mr *MockRefreshTokenRepoMockRecorder) RevokeByID(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByID", reflect.TypeOf((*MockRefreshTokenRepo)(nil).RevokeByID), ctx, tokenID)
}

// Rotate mocks base method.
func (m *MockRefreshTokenRepo) Rotate(ctx context.Context, oldTokenID, newTokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx, oldTokenID, newTokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rotate indicates an expected call of Rotate.
func (mr *MockRefreshTokenRepoMockRecorder) Rotate(ctx, oldTokenID, newTokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockRefreshTokenRepo)(nil).Rotate), ctx, oldTokenID, newTokenID)
}

// MockAccountRepo is a mock of AccountRepo interface.
type MockAccountRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepoMockRecorder
	isgomock struct{}
}

// MockAccountRepoMockRecorder is the mock recorder for MockAccountRepo.
type MockAccountRepoMockRecorder struct {
	mock *MockAccountRepo
}

// NewMockAccountRepo creates a new mock instance.
func NewMockAccountRepo(ctrl *gomock.Controller) *MockAccountRepo {
	mock := &MockAccountRepo{ctrl: ctrl}
	mock.recorder = &MockAccountRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepo) EXPECT() *MockAccountRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAccountRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAccountRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccountRepo)(nil).Delete), ctx, id)
}

// GetByProvider mocks base method.
func (m *MockAccountRepo) GetByProvider(ctx context.Context, provider, providerAccountID string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProvider", ctx, provider, providerAccountID)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProvider indicates an expected call of GetByProvider.
func (mr *MockAccountRepoMockRecorder) GetByProvider(ctx, provider, providerAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProvider", reflect.TypeOf((*MockAccountRepo)(nil).GetByProvider), ctx, provider, providerAccountID)
}

// ListByUser mocks base method.
func (m *MockAccountRepo) ListByUser(ctx context.Context, userID string) ([]models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockAccountRepoMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockAccountRepo)(nil).ListByUser), ctx, userID)
}

// Upsert mocks base method.
func (m *MockAccountRepo) Upsert(ctx context.Context, userID, provider, providerAccountID string, accessToken, refreshToken *string, expiresAt *int) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, userID, provider, providerAccountID, accessToken, refreshToken, expiresAt)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockAccountRepoMockRecorder) Upsert(ctx, userID, provider, providerAccountID, accessToken, refreshToken, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockAccountRepo)(nil).Upsert), ctx, userID, provider, providerAccountID, accessToken, refreshToken, expiresAt)
}

// MockAuditRepo is a mock of AuditRepo interface.
type MockAuditRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepoMockRecorder
	isgomock struct{}
}

// MockAuditRepoMockRecorder is the mock recorder for MockAuditRepo.
type MockAuditRepoMockRecorder struct {
	mock *MockAuditRepo
}

// NewMockAuditRepo creates a new mock instance.
func NewMockAuditRepo(ctrl *gomock.Controller) *MockAuditRepo {
	mock := &MockAuditRepo{ctrl: ctrl}
	mock.recorder = &MockAuditRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepo) EXPECT() *MockAuditRepoMockRecorder {
	return m.recorder
}

// CountAll mocks base method.
func (m *MockAuditRepo) CountAll(ctx context.Context) (*repository.SystemCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAll", ctx)
	ret0, _ := ret[0].(*repository.SystemCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAll indicates an expected call of CountAll.
func (mr *MockAuditRepoMockRecorder) CountAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAll", reflect.TypeOf((*MockAuditRepo)(nil).CountAll), ctx)
}

// CountAllByOrg mocks base method.
func (m *MockAuditRepo) CountAllByOrg(ctx context.Context, orgID string) (string, *repository.OrgCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAllByOrg", ctx, orgID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*repository.OrgCounts)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CountAllByOrg indicates an expected call of CountAllByOrg.
func (mr *MockAuditRepoMockRecorder) CountAllByOrg(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAllByOrg", reflect.TypeOf((*MockAuditRepo)(nil).CountAllByOrg), ctx, orgID)
}

// GetDatabaseStats mocks base method.
func (m *MockAuditRepo) GetDatabaseStats(ctx context.Context) (*repository.DatabaseStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseStats", ctx)
	ret0, _ := ret[0].(*repository.DatabaseStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseStats indicates an expected call of GetDatabaseStats.
func (mr *MockAuditRepoMockRecorder) GetDatabaseStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseStats", reflect.TypeOf((*MockAuditRepo)(nil).GetDatabaseStats), ctx)
}

// GetSystemStats mocks base method.
func (m *MockAuditRepo) GetSystemStats(ctx context.Context) (*repository.SystemStatsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemStats", ctx)
	ret0, _ := ret[0].(*repository.SystemStatsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemStats indicates an expected call of GetSystemStats.
func (mr *MockAuditRepoMockRecorder) GetSystemStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemStats", reflect.TypeOf((*MockAuditRepo)(nil).GetSystemStats), ctx)
}

// GlobalCRUDBreakdown mocks base method.
func (m *MockAuditRepo) GlobalCRUDBreakdown(ctx context.Context) (*repository.CRUDBreakdown, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalCRUDBreakdown", ctx)
	ret0, _ := ret[0].(*repository.CRUDBreakdown)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GlobalCRUDBreakdown indicates an expected call of GlobalCRUDBreakdown.
func (mr *MockAuditRepoMockRecorder) GlobalCRUDBreakdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalCRUDBreakdown", reflect.TypeOf((*MockAuditRepo)(nil).GlobalCRUDBreakdown), ctx)
}

// OrgCRUDBreakdown mocks base method.
func (m *MockAuditRepo) OrgCRUDBreakdown(ctx context.Context, orgID string) (*repository.CRUDBreakdown, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrgCRUDBreakdown", ctx, orgID)
	ret0, _ := ret[0].(*repository.CRUDBreakdown)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrgCRUDBreakdown indicates an expected call of OrgCRUDBreakdown.
func (mr *MockAuditRepoMockRecorder) OrgCRUDBreakdown(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrgCRUDBreakdown", reflect.TypeOf((*MockAuditRepo)(nil).OrgCRUDBreakdown), ctx, orgID)
}

// Log mocks base method.
func (m *MockAuditRepo) Log(ctx context.Context, orgID string, actorID *string, action, targetType, targetID string, ip, userAgent *string, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", ctx, orgID, actorID, action, targetType, targetID, ip, userAgent, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// Log indicates an expected call of Log.
func (mr *MockAuditRepoMockRecorder) Log(ctx, orgID, actorID, action, targetType, targetID, ip, userAgent, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockAuditRepo)(nil).Log), ctx, orgID, actorID, action, targetType, targetID, ip, userAgent, metadata)
}

// PurgeOlderThan mocks base method.
func (m *MockAuditRepo) PurgeOlderThan(ctx context.Context, orgID string, cutoff time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeOlderThan", ctx, orgID, cutoff)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgeOlderThan indicates an expected call of PurgeOlderThan.
func (mr *MockAuditRepoMockRecorder) PurgeOlderThan(ctx, orgID, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeOlderThan", reflect.TypeOf((*MockAuditRepo)(nil).PurgeOlderThan), ctx, orgID, cutoff)
}

// Query mocks base method.
func (m *MockAuditRepo) Query(ctx context.Context, params repository.AuditQueryParams) (*repository.AuditQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, params)
	ret0, _ := ret[0].(*repository.AuditQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockAuditRepoMockRecorder) Query(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockAuditRepo)(nil).Query), ctx, params)
}

// Stats mocks base method.
func (m *MockAuditRepo) Stats(ctx context.Context, orgID string, since time.Time) (*repository.AuditStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx, orgID, since)
	ret0, _ := ret[0].(*repository.AuditStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockAuditRepoMockRecorder) Stats(ctx, orgID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockAuditRepo)(nil).Stats), ctx, orgID, since)
}

// MockOrgRepo is a mock of OrgRepo interface.
type MockOrgRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOrgRepoMockRecorder
	isgomock struct{}
}

// MockOrgRepoMockRecorder is the mock recorder for MockOrgRepo.
type MockOrgRepoMockRecorder struct {
	mock *MockOrgRepo
}

// NewMockOrgRepo creates a new mock instance.
func NewMockOrgRepo(ctrl *gomock.Controller) *MockOrgRepo {
	mock := &MockOrgRepo{ctrl: ctrl}
	mock.recorder = &MockOrgRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrgRepo) EXPECT() *MockOrgRepoMockRecorder {
	return m.recorder
}

// BoardCount mocks base method.
func (m *MockOrgRepo) BoardCount(ctx context.Context, orgID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BoardCount", ctx, orgID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BoardCount indicates an expected call of BoardCount.
func (mr *MockOrgRepoMockRecorder) BoardCount(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BoardCount", reflect.TypeOf((*MockOrgRepo)(nil).BoardCount), ctx, orgID)
}

// Create mocks base method.
func (m *MockOrgRepo) Create(ctx context.Context, name, slug string) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, slug)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrgRepoMockRecorder) Create(ctx, name, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrgRepo)(nil).Create), ctx, name, slug)
}

// CreateInTx mocks base method.
func (m *MockOrgRepo) CreateInTx(ctx context.Context, tx pgx.Tx, name, slug string) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInTx", ctx, tx, name, slug)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInTx indicates an expected call of CreateInTx.
func (mr *MockOrgRepoMockRecorder) CreateInTx(ctx, tx, name, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInTx", reflect.TypeOf((*MockOrgRepo)(nil).CreateInTx), ctx, tx, name, slug)
}

// Delete mocks base method.
func (m *MockOrgRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrgRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrgRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockOrgRepo) GetByID(ctx context.Context, id string) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrgRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrgRepo)(nil).GetByID), ctx, id)
}

// ListByUser mocks base method.
func (m *MockOrgRepo) ListByUser(ctx context.Context, userID string) ([]repository.OrgWithCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]repository.OrgWithCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockOrgRepoMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockOrgRepo)(nil).ListByUser), ctx, userID)
}

// SlugExists mocks base method.
func (m *MockOrgRepo) SlugExists(ctx context.Context, slug string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SlugExists", ctx, slug)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SlugExists indicates an expected call of SlugExists.
func (mr *MockOrgRepoMockRecorder) SlugExists(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SlugExists", reflect.TypeOf((*MockOrgRepo)(nil).SlugExists), ctx, slug)
}

// Update mocks base method.
func (m *MockOrgRepo) Update(ctx context.Context, id, name string) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, name)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOrgRepoMockRecorder) Update(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrgRepo)(nil).Update), ctx, id, name)
}

// MockMembershipRepo is a mock of MembershipRepo interface.
type MockMembershipRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipRepoMockRecorder
	isgomock struct{}
}

// MockMembershipRepoMockRecorder is the mock recorder for MockMembershipRepo.
type MockMembershipRepoMockRecorder struct {
	mock *MockMembershipRepo
}

// NewMockMembershipRepo creates a new mock instance.
func NewMockMembershipRepo(ctrl *gomock.Controller) *MockMembershipRepo {
	mock := &MockMembershipRepo{ctrl: ctrl}
	mock.recorder = &MockMembershipRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipRepo) EXPECT() *MockMembershipRepoMockRecorder {
	return m.recorder
}

// CountByUser mocks base method.
func (m *MockMembershipRepo) CountByUser(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUser", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUser indicates an expected call of CountByUser.
func (mr *MockMembershipRepoMockRecorder) CountByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUser", reflect.TypeOf((*MockMembershipRepo)(nil).CountByUser), ctx, userID)
}

// Create mocks base method.
func (m *MockMembershipRepo) Create(ctx context.Context, orgID, userID string, role models.OrgRole) (*models.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orgID, userID, role)
	ret0, _ := ret[0].(*models.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMembershipRepoMockRecorder) Create(ctx, orgID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMembershipRepo)(nil).Create), ctx, orgID, userID, role)
}

// CreateInTx mocks base method.
func (m *MockMembershipRepo) CreateInTx(ctx context.Context, tx pgx.Tx, orgID, userID string, role models.OrgRole) (*models.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInTx", ctx, tx, orgID, userID, role)
	ret0, _ := ret[0].(*models.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInTx indicates an expected call of CreateInTx.
func (mr *MockMembershipRepoMockRecorder) CreateInTx(ctx, tx, orgID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInTx", reflect.TypeOf((*MockMembershipRepo)(nil).CreateInTx), ctx, tx, orgID, userID, role)
}

// Delete mocks base method.
func (m *MockMembershipRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMembershipRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMembershipRepo)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockMembershipRepo) Exists(ctx context.Context, orgID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, orgID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockMembershipRepoMockRecorder) Exists(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockMembershipRepo)(nil).Exists), ctx, orgID, userID)
}

// GetByID mocks base method.
func (m *MockMembershipRepo) GetByID(ctx context.Context, id string) (*models.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMembershipRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMembershipRepo)(nil).GetByID), ctx, id)
}

// GetByOrgAndUser mocks base method.
func (m *MockMembershipRepo) GetByOrgAndUser(ctx context.Context, orgID, userID string) (*models.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrgAndUser", ctx, orgID, userID)
	ret0, _ := ret[0].(*models.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrgAndUser indicates an expected call of GetByOrgAndUser.
func (mr *MockMembershipRepoMockRecorder) GetByOrgAndUser(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrgAndUser", reflect.TypeOf((*MockMembershipRepo)(nil).GetByOrgAndUser), ctx, orgID, userID)
}

// ListByOrg mocks base method.
func (m *MockMembershipRepo) ListByOrg(ctx context.Context, orgID string) ([]models.MembershipWithUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrg", ctx, orgID)
	ret0, _ := ret[0].([]models.MembershipWithUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByOrg indicates an expected call of ListByOrg.
func (mr *MockMembershipRepoMockRecorder) ListByOrg(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrg", reflect.TypeOf((*MockMembershipRepo)(nil).ListByOrg), ctx, orgID)
}

// UpdateRole mocks base method.
func (m *MockMembershipRepo) UpdateRole(ctx context.Context, id string, role models.OrgRole) (*models.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, id, role)
	ret0, _ := ret[0].(*models.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockMembershipRepoMockRecorder) UpdateRole(ctx, id, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockMembershipRepo)(nil).UpdateRole), ctx, id, role)
}

// MockBoardRepo is a mock of BoardRepo interface.
type MockBoardRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBoardRepoMockRecorder
	isgomock struct{}
}

// MockBoardRepoMockRecorder is the mock recorder for MockBoardRepo.
type MockBoardRepoMockRecorder struct {
	mock *MockBoardRepo
}

// NewMockBoardRepo creates a new mock instance.
func NewMockBoardRepo(ctrl *gomock.Controller) *MockBoardRepo {
	mock := &MockBoardRepo{ctrl: ctrl}
	mock.recorder = &MockBoardRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardRepo) EXPECT() *MockBoardRepoMockRecorder {
	return m.recorder
}

// CreateInTx mocks base method.
func (m *MockBoardRepo) CreateInTx(ctx context.Context, tx pgx.Tx, board *models.Board) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInTx", ctx, tx, board)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInTx indicates an expected call of CreateInTx.
func (mr *MockBoardRepoMockRecorder) CreateInTx(ctx, tx, board any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInTx", reflect.TypeOf((*MockBoardRepo)(nil).CreateInTx), ctx, tx, board)
}

// Delete mocks base method.
func (m *MockBoardRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBoardRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBoardRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockBoardRepo) GetByID(ctx context.Context, id string) (*models.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBoardRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBoardRepo)(nil).GetByID), ctx, id)
}

// GetByIDForUpdate mocks base method.
func (m *MockBoardRepo) GetByIDForUpdate(ctx context.Context, tx pgx.Tx, id string) (*models.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDForUpdate", ctx, tx, id)
	ret0, _ := ret[0].(*models.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDForUpdate indicates an expected call of GetByIDForUpdate.
func (mr *MockBoardRepoMockRecorder) GetByIDForUpdate(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDForUpdate", reflect.TypeOf((*MockBoardRepo)(nil).GetByIDForUpdate), ctx, tx, id)
}

// GetByIDWithVersion mocks base method.
func (m *MockBoardRepo) GetByIDWithVersion(ctx context.Context, id string) (*models.BoardWithVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDWithVersion", ctx, id)
	ret0, _ := ret[0].(*models.BoardWithVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDWithVersion indicates an expected call of GetByIDWithVersion.
func (mr *MockBoardRepoMockRecorder) GetByIDWithVersion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDWithVersion", reflect.TypeOf((*MockBoardRepo)(nil).GetByIDWithVersion), ctx, id)
}

// Search mocks base method.
func (m *MockBoardRepo) Search(ctx context.Context, params repository.BoardSearchParams) (*repository.BoardSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, params)
	ret0, _ := ret[0].(*repository.BoardSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockBoardRepoMockRecorder) Search(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockBoardRepo)(nil).Search), ctx, params)
}

// Update mocks base method.
func (m *MockBoardRepo) Update(ctx context.Context, board *models.Board) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, board)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBoardRepoMockRecorder) Update(ctx, board any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBoardRepo)(nil).Update), ctx, board)
}

// UpdateVersionInfoInTx mocks base method.
func (m *MockBoardRepo) UpdateVersionInfoInTx(ctx context.Context, tx pgx.Tx, boardID, versionID, etag string, versionNumber int, searchContent, thumbnail *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVersionInfoInTx", ctx, tx, boardID, versionID, etag, versionNumber, searchContent, thumbnail)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVersionInfoInTx indicates an expected call of UpdateVersionInfoInTx.
func (mr *MockBoardRepoMockRecorder) UpdateVersionInfoInTx(ctx, tx, boardID, versionID, etag, versionNumber, searchContent, thumbnail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVersionInfoInTx", reflect.TypeOf((*MockBoardRepo)(nil).UpdateVersionInfoInTx), ctx, tx, boardID, versionID, etag, versionNumber, searchContent, thumbnail)
}

// MockBoardVersionRepo is a mock of BoardVersionRepo interface.
type MockBoardVersionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBoardVersionRepoMockRecorder
	isgomock struct{}
}

// MockBoardVersionRepoMockRecorder is the mock recorder for MockBoardVersionRepo.
type MockBoardVersionRepoMockRecorder struct {
	mock *MockBoardVersionRepo
}

// NewMockBoardVersionRepo creates a new mock instance.
func NewMockBoardVersionRepo(ctrl *gomock.Controller) *MockBoardVersionRepo {
	mock := &MockBoardVersionRepo{ctrl: ctrl}
	mock.recorder = &MockBoardVersionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardVersionRepo) EXPECT() *MockBoardVersionRepoMockRecorder {
	return m.recorder
}

// CreateInTx mocks base method.
func (m *MockBoardVersionRepo) CreateInTx(ctx context.Context, tx pgx.Tx, v *models.BoardVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInTx", ctx, tx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInTx indicates an expected call of CreateInTx.
func (mr *MockBoardVersionRepoMockRecorder) CreateInTx(ctx, tx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInTx", reflect.TypeOf((*MockBoardVersionRepo)(nil).CreateInTx), ctx, tx, v)
}

// DataStorageByBoard mocks base method.
func (m *MockBoardVersionRepo) DataStorageByBoard(ctx context.Context, boardID string) (*repository.BoardDataStorageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataStorageByBoard", ctx, boardID)
	ret0, _ := ret[0].(*repository.BoardDataStorageInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DataStorageByBoard indicates an expected call of DataStorageByBoard.
func (mr *MockBoardVersionRepoMockRecorder) DataStorageByBoard(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataStorageByBoard", reflect.TypeOf((*MockBoardVersionRepo)(nil).DataStorageByBoard), ctx, boardID)
}

// DataStorageByOrg mocks base method.
func (m *MockBoardVersionRepo) DataStorageByOrg(ctx context.Context, orgID string) (*repository.BoardDataStorageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataStorageByOrg", ctx, orgID)
	ret0, _ := ret[0].(*repository.BoardDataStorageInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DataStorageByOrg indicates an expected call of DataStorageByOrg.
func (mr *MockBoardVersionRepoMockRecorder) DataStorageByOrg(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataStorageByOrg", reflect.TypeOf((*MockBoardVersionRepo)(nil).DataStorageByOrg), ctx, orgID)
}

// GetByBoardAndVersion mocks base method.
func (m *MockBoardVersionRepo) GetByBoardAndVersion(ctx context.Context, boardID string, version int) (*models.BoardVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBoardAndVersion", ctx, boardID, version)
	ret0, _ := ret[0].(*models.BoardVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBoardAndVersion indicates an expected call of GetByBoardAndVersion.
func (mr *MockBoardVersionRepoMockRecorder) GetByBoardAndVersion(ctx, boardID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBoardAndVersion", reflect.TypeOf((*MockBoardVersionRepo)(nil).GetByBoardAndVersion), ctx, boardID, version)
}

// GetByID mocks base method.
func (m *MockBoardVersionRepo) GetByID(ctx context.Context, id string) (*models.BoardVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.BoardVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBoardVersionRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBoardVersionRepo)(nil).GetByID), ctx, id)
}

// ListByBoard mocks base method.
func (m *MockBoardVersionRepo) ListByBoard(ctx context.Context, boardID string, limit, offset int) ([]repository.BoardVersionWithCreator, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByBoard", ctx, boardID, limit, offset)
	ret0, _ := ret[0].([]repository.BoardVersionWithCreator)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByBoard indicates an expected call of ListByBoard.
func (mr *MockBoardVersionRepoMockRecorder) ListByBoard(ctx, boardID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByBoard", reflect.TypeOf((*MockBoardVersionRepo)(nil).ListByBoard), ctx, boardID, limit, offset)
}

// PruneOldVersions mocks base method.
func (m *MockBoardVersionRepo) PruneOldVersions(ctx context.Context, boardID string, maxKeep int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneOldVersions", ctx, boardID, maxKeep)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PruneOldVersions indicates an expected call of PruneOldVersions.
func (mr *MockBoardVersionRepoMockRecorder) PruneOldVersions(ctx, boardID, maxKeep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneOldVersions", reflect.TypeOf((*MockBoardVersionRepo)(nil).PruneOldVersions), ctx, boardID, maxKeep)
}

// MockBoardPermissionRepo is a mock of BoardPermissionRepo interface.
type MockBoardPermissionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBoardPermissionRepoMockRecorder
	isgomock struct{}
}

// MockBoardPermissionRepoMockRecorder is the mock recorder for MockBoardPermissionRepo.
type MockBoardPermissionRepoMockRecorder struct {
	mock *MockBoardPermissionRepo
}

// NewMockBoardPermissionRepo creates a new mock instance.
func NewMockBoardPermissionRepo(ctrl *gomock.Controller) *MockBoardPermissionRepo {
	mock := &MockBoardPermissionRepo{ctrl: ctrl}
	mock.recorder = &MockBoardPermissionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardPermissionRepo) EXPECT() *MockBoardPermissionRepoMockRecorder {
	return m.recorder
}

// GetByBoardAndUser mocks base method.
func (m *MockBoardPermissionRepo) GetByBoardAndUser(ctx context.Context, boardID, userID string) (*models.BoardPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBoardAndUser", ctx, boardID, userID)
	ret0, _ := ret[0].(*models.BoardPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBoardAndUser indicates an expected call of GetByBoardAndUser.
func (mr *MockBoardPermissionRepoMockRecorder) GetByBoardAndUser(ctx, boardID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBoardAndUser", reflect.TypeOf((*MockBoardPermissionRepo)(nil).GetByBoardAndUser), ctx, boardID, userID)
}

// MockBoardAssetRepo is a mock of BoardAssetRepo interface.
type MockBoardAssetRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBoardAssetRepoMockRecorder
	isgomock struct{}
}

// MockBoardAssetRepoMockRecorder is the mock recorder for MockBoardAssetRepo.
type MockBoardAssetRepoMockRecorder struct {
	mock *MockBoardAssetRepo
}

// NewMockBoardAssetRepo creates a new mock instance.
func NewMockBoardAssetRepo(ctrl *gomock.Controller) *MockBoardAssetRepo {
	mock := &MockBoardAssetRepo{ctrl: ctrl}
	mock.recorder = &MockBoardAssetRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardAssetRepo) EXPECT() *MockBoardAssetRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBoardAssetRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBoardAssetRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBoardAssetRepo)(nil).Delete), ctx, id)
}

// DeleteByBoardAndFileID mocks base method.
func (m *MockBoardAssetRepo) DeleteByBoardAndFileID(ctx context.Context, boardID, fileID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByBoardAndFileID", ctx, boardID, fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByBoardAndFileID indicates an expected call of DeleteByBoardAndFileID.
func (mr *MockBoardAssetRepoMockRecorder) DeleteByBoardAndFileID(ctx, boardID, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByBoardAndFileID", reflect.TypeOf((*MockBoardAssetRepo)(nil).DeleteByBoardAndFileID), ctx, boardID, fileID)
}

// DeleteOrphaned mocks base method.
func (m *MockBoardAssetRepo) DeleteOrphaned(ctx context.Context, boardID string, activeFileIDs []string) ([]models.BoardAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrphaned", ctx, boardID, activeFileIDs)
	ret0, _ := ret[0].([]models.BoardAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOrphaned indicates an expected call of DeleteOrphaned.
func (mr *MockBoardAssetRepoMockRecorder) DeleteOrphaned(ctx, boardID, activeFileIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrphaned", reflect.TypeOf((*MockBoardAssetRepo)(nil).DeleteOrphaned), ctx, boardID, activeFileIDs)
}

// FindBySHA256 mocks base method.
func (m *MockBoardAssetRepo) FindBySHA256(ctx context.Context, boardID, sha256 string) (*models.BoardAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySHA256", ctx, boardID, sha256)
	ret0, _ := ret[0].(*models.BoardAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySHA256 indicates an expected call of FindBySHA256.
func (mr *MockBoardAssetRepoMockRecorder) FindBySHA256(ctx, boardID, sha256 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySHA256", reflect.TypeOf((*MockBoardAssetRepo)(nil).FindBySHA256), ctx, boardID, sha256)
}

// GetByBoardAndFileID mocks base method.
func (m *MockBoardAssetRepo) GetByBoardAndFileID(ctx context.Context, boardID, fileID string) (*models.BoardAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBoardAndFileID", ctx, boardID, fileID)
	ret0, _ := ret[0].(*models.BoardAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBoardAndFileID indicates an expected call of GetByBoardAndFileID.
func (mr *MockBoardAssetRepoMockRecorder) GetByBoardAndFileID(ctx, boardID, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBoardAndFileID", reflect.TypeOf((*MockBoardAssetRepo)(nil).GetByBoardAndFileID), ctx, boardID, fileID)
}

// ListByBoard mocks base method.
func (m *MockBoardAssetRepo) ListByBoard(ctx context.Context, boardID string) ([]models.BoardAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByBoard", ctx, boardID)
	ret0, _ := ret[0].([]models.BoardAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByBoard indicates an expected call of ListByBoard.
func (mr *MockBoardAssetRepoMockRecorder) ListByBoard(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByBoard", reflect.TypeOf((*MockBoardAssetRepo)(nil).ListByBoard), ctx, boardID)
}

// StorageUsedByBoard mocks base method.
func (m *MockBoardAssetRepo) StorageUsedByBoard(ctx context.Context, boardID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageUsedByBoard", ctx, boardID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StorageUsedByBoard indicates an expected call of StorageUsedByBoard.
func (mr *MockBoardAssetRepoMockRecorder) StorageUsedByBoard(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageUsedByBoard", reflect.TypeOf((*MockBoardAssetRepo)(nil).StorageUsedByBoard), ctx, boardID)
}

// StorageUsedByOrg mocks base method.
func (m *MockBoardAssetRepo) StorageUsedByOrg(ctx context.Context, orgID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageUsedByOrg", ctx, orgID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StorageUsedByOrg indicates an expected call of StorageUsedByOrg.
func (mr *MockBoardAssetRepoMockRecorder) StorageUsedByOrg(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageUsedByOrg", reflect.TypeOf((*MockBoardAssetRepo)(nil).StorageUsedByOrg), ctx, orgID)
}

// Upsert mocks base method.
func (m *MockBoardAssetRepo) Upsert(ctx context.Context, asset *models.BoardAsset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, asset)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockBoardAssetRepoMockRecorder) Upsert(ctx, asset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockBoardAssetRepo)(nil).Upsert), ctx, asset)
}

// MockShareLinkRepo is a mock of ShareLinkRepo interface.
type MockShareLinkRepo struct {
	ctrl     *gomock.Controller
	recorder *MockShareLinkRepoMockRecorder
	isgomock struct{}
}

// MockShareLinkRepoMockRecorder is the mock recorder for MockShareLinkRepo.
type MockShareLinkRepoMockRecorder struct {
	mock *MockShareLinkRepo
}

// NewMockShareLinkRepo creates a new mock instance.
func NewMockShareLinkRepo(ctrl *gomock.Controller) *MockShareLinkRepo {
	mock := &MockShareLinkRepo{ctrl: ctrl}
	mock.recorder = &MockShareLinkRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShareLinkRepo) EXPECT() *MockShareLinkRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShareLinkRepo) Create(ctx context.Context, boardID, createdBy string, role models.BoardRole, expiresAt *time.Time) (*models.ShareLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, boardID, createdBy, role, expiresAt)
	ret0, _ := ret[0].(*models.ShareLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockShareLinkRepoMockRecorder) Create(ctx, boardID, createdBy, role, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShareLinkRepo)(nil).Create), ctx, boardID, createdBy, role, expiresAt)
}

// Delete mocks base method.
func (m *MockShareLinkRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShareLinkRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShareLinkRepo)(nil).Delete), ctx, id)
}

// DeleteByBoard mocks base method.
func (m *MockShareLinkRepo) DeleteByBoard(ctx context.Context, boardID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByBoard", ctx, boardID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByBoard indicates an expected call of DeleteByBoard.
func (mr *MockShareLinkRepoMockRecorder) DeleteByBoard(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByBoard", reflect.TypeOf((*MockShareLinkRepo)(nil).DeleteByBoard), ctx, boardID)
}

// DeleteExpired mocks base method.
func (m *MockShareLinkRepo) DeleteExpired(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockShareLinkRepoMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockShareLinkRepo)(nil).DeleteExpired), ctx)
}

// GetByID mocks base method.
func (m *MockShareLinkRepo) GetByID(ctx context.Context, id string) (*models.ShareLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.ShareLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockShareLinkRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockShareLinkRepo)(nil).GetByID), ctx, id)
}

// GetByToken mocks base method.
func (m *MockShareLinkRepo) GetByToken(ctx context.Context, tok string) (*models.ShareLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, tok)
	ret0, _ := ret[0].(*models.ShareLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockShareLinkRepoMockRecorder) GetByToken(ctx, tok any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockShareLinkRepo)(nil).GetByToken), ctx, tok)
}

// ListByBoard mocks base method.
func (m *MockShareLinkRepo) ListByBoard(ctx context.Context, boardID string) ([]models.ShareLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByBoard", ctx, boardID)
	ret0, _ := ret[0].([]models.ShareLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByBoard indicates an expected call of ListByBoard.
func (mr *MockShareLinkRepoMockRecorder) ListByBoard(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByBoard", reflect.TypeOf((*MockShareLinkRepo)(nil).ListByBoard), ctx, boardID)
}

// MockBackupRepo is a mock of BackupRepo interface.
type MockBackupRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBackupRepoMockRecorder
	isgomock struct{}
}

// MockBackupRepoMockRecorder is the mock recorder for MockBackupRepo.
type MockBackupRepoMockRecorder struct {
	mock *MockBackupRepo
}

// NewMockBackupRepo creates a new mock instance.
func NewMockBackupRepo(ctrl *gomock.Controller) *MockBackupRepo {
	mock := &MockBackupRepo{ctrl: ctrl}
	mock.recorder = &MockBackupRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupRepo) EXPECT() *MockBackupRepoMockRecorder {
	return m.recorder
}

// CompleteMetadata mocks base method.
func (m *MockBackupRepo) CompleteMetadata(ctx context.Context, id, filename, storageKey string, sizeBytes int64, durationMs int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteMetadata", ctx, id, filename, storageKey, sizeBytes, durationMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteMetadata indicates an expected call of CompleteMetadata.
func (mr *MockBackupRepoMockRecorder) CompleteMetadata(ctx, id, filename, storageKey, sizeBytes, durationMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMetadata", reflect.TypeOf((*MockBackupRepo)(nil).CompleteMetadata), ctx, id, filename, storageKey, sizeBytes, durationMs)
}

// CreateMetadata mocks base method.
func (m *MockBackupRepo) CreateMetadata(ctx context.Context, backupType string) (*models.BackupMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMetadata", ctx, backupType)
	ret0, _ := ret[0].(*models.BackupMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMetadata indicates an expected call of CreateMetadata.
func (mr *MockBackupRepoMockRecorder) CreateMetadata(ctx, backupType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMetadata", reflect.TypeOf((*MockBackupRepo)(nil).CreateMetadata), ctx, backupType)
}

// DeleteMetadata mocks base method.
func (m *MockBackupRepo) DeleteMetadata(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMetadata", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMetadata indicates an expected call of DeleteMetadata.
func (mr *MockBackupRepoMockRecorder) DeleteMetadata(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMetadata", reflect.TypeOf((*MockBackupRepo)(nil).DeleteMetadata), ctx, id)
}

// FailMetadata mocks base method.
func (m *MockBackupRepo) FailMetadata(ctx context.Context, id, errMsg string, durationMs int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailMetadata", ctx, id, errMsg, durationMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailMetadata indicates an expected call of FailMetadata.
func (mr *MockBackupRepoMockRecorder) FailMetadata(ctx, id, errMsg, durationMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailMetadata", reflect.TypeOf((*MockBackupRepo)(nil).FailMetadata), ctx, id, errMsg, durationMs)
}

// GetMetadata mocks base method.
func (m *MockBackupRepo) GetMetadata(ctx context.Context, id string) (*models.BackupMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx, id)
	ret0, _ := ret[0].(*models.BackupMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockBackupRepoMockRecorder) GetMetadata(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockBackupRepo)(nil).GetMetadata), ctx, id)
}

// GetSchedule mocks base method.
func (m *MockBackupRepo) GetSchedule(ctx context.Context) (*models.BackupSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchedule", ctx)
	ret0, _ := ret[0].(*models.BackupSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchedule indicates an expected call of GetSchedule.
func (mr *MockBackupRepoMockRecorder) GetSchedule(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchedule", reflect.TypeOf((*MockBackupRepo)(nil).GetSchedule), ctx)
}

// ListExpiredForRotation mocks base method.
func (m *MockBackupRepo) ListExpiredForRotation(ctx context.Context, keepDaily, keepWeekly, keepMonthly int) ([]models.BackupMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredForRotation", ctx, keepDaily, keepWeekly, keepMonthly)
	ret0, _ := ret[0].([]models.BackupMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredForRotation indicates an expected call of ListExpiredForRotation.
func (mr *MockBackupRepoMockRecorder) ListExpiredForRotation(ctx, keepDaily, keepWeekly, keepMonthly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredForRotation", reflect.TypeOf((*MockBackupRepo)(nil).ListExpiredForRotation), ctx, keepDaily, keepWeekly, keepMonthly)
}

// ListMetadata mocks base method.
func (m *MockBackupRepo) ListMetadata(ctx context.Context, limit, offset int) ([]models.BackupMetadata, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMetadata", ctx, limit, offset)
	ret0, _ := ret[0].([]models.BackupMetadata)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMetadata indicates an expected call of ListMetadata.
func (mr *MockBackupRepoMockRecorder) ListMetadata(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMetadata", reflect.TypeOf((*MockBackupRepo)(nil).ListMetadata), ctx, limit, offset)
}

// UpdateSchedule mocks base method.
func (m *MockBackupRepo) UpdateSchedule(ctx context.Context, enabled bool, cronExpr string, keepDaily, keepWeekly, keepMonthly int) (*models.BackupSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchedule", ctx, enabled, cronExpr, keepDaily, keepWeekly, keepMonthly)
	ret0, _ := ret[0].(*models.BackupSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSchedule indicates an expected call of UpdateSchedule.
func (mr *MockBackupRepoMockRecorder) UpdateSchedule(ctx, enabled, cronExpr, keepDaily, keepWeekly, keepMonthly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedule", reflect.TypeOf((*MockBackupRepo)(nil).UpdateSchedule), ctx, enabled, cronExpr, keepDaily, keepWeekly, keepMonthly)
}
