// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/darwinbatres/drawgo/backend/internal/storage (interfaces: ObjectStorage)
//
// Generated by this command:
//
//	mockgen -destination=internal/testutil/mocks/mock_storage.go -package=mocks github.com/darwinbatres/drawgo/backend/internal/storage ObjectStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	v7 "github.com/minio/minio-go/v7"
	gomock "go.uber.org/mock/gomock"

	"github.com/darwinbatres/drawgo/backend/internal/storage"
)

// MockObjectStorage is a mock of ObjectStorage interface.
type MockObjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageMockRecorder
	isgomock struct{}
}

// MockObjectStorageMockRecorder is the mock recorder for MockObjectStorage.
type MockObjectStorageMockRecorder struct {
	mock *MockObjectStorage
}

// NewMockObjectStorage creates a new mock instance.
func NewMockObjectStorage(ctrl *gomock.Controller) *MockObjectStorage {
	mock := &MockObjectStorage{ctrl: ctrl}
	mock.recorder = &MockObjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorage) EXPECT() *MockObjectStorageMockRecorder {
	return m.recorder
}

// BucketStats mocks base method.
func (m *MockObjectStorage) BucketStats(ctx context.Context, bucket string) (*storage.BucketStatsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BucketStats", ctx, bucket)
	ret0, _ := ret[0].(*storage.BucketStatsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BucketStats indicates an expected call of BucketStats.
func (mr *MockObjectStorageMockRecorder) BucketStats(ctx, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BucketStats", reflect.TypeOf((*MockObjectStorage)(nil).BucketStats), ctx, bucket)
}

// Delete mocks base method.
func (m *MockObjectStorage) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockObjectStorageMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockObjectStorage)(nil).Delete), ctx, key)
}

// DeleteFromBucket mocks base method.
func (m *MockObjectStorage) DeleteFromBucket(ctx context.Context, bucket, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFromBucket", ctx, bucket, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFromBucket indicates an expected call of DeleteFromBucket.
func (mr *MockObjectStorageMockRecorder) DeleteFromBucket(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFromBucket", reflect.TypeOf((*MockObjectStorage)(nil).DeleteFromBucket), ctx, bucket, key)
}

// Download mocks base method.
func (m *MockObjectStorage) Download(ctx context.Context, key string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockObjectStorageMockRecorder) Download(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockObjectStorage)(nil).Download), ctx, key)
}

// DownloadFromBucket mocks base method.
func (m *MockObjectStorage) DownloadFromBucket(ctx context.Context, bucket, key string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFromBucket", ctx, bucket, key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFromBucket indicates an expected call of DownloadFromBucket.
func (mr *MockObjectStorageMockRecorder) DownloadFromBucket(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFromBucket", reflect.TypeOf((*MockObjectStorage)(nil).DownloadFromBucket), ctx, bucket, key)
}

// ListObjects mocks base method.
func (m *MockObjectStorage) ListObjects(ctx context.Context, bucket, prefix string) ([]v7.ObjectInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, bucket, prefix)
	ret0, _ := ret[0].([]v7.ObjectInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockObjectStorageMockRecorder) ListObjects(ctx, bucket, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockObjectStorage)(nil).ListObjects), ctx, bucket, prefix)
}

// PresignedURL mocks base method.
func (m *MockObjectStorage) PresignedURL(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedURL", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedURL indicates an expected call of PresignedURL.
func (mr *MockObjectStorageMockRecorder) PresignedURL(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedURL", reflect.TypeOf((*MockObjectStorage)(nil).PresignedURL), ctx, key)
}

// PresignedURLFromBucket mocks base method.
func (m *MockObjectStorage) PresignedURLFromBucket(ctx context.Context, bucket, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedURLFromBucket", ctx, bucket, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedURLFromBucket indicates an expected call of PresignedURLFromBucket.
func (mr *MockObjectStorageMockRecorder) PresignedURLFromBucket(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedURLFromBucket", reflect.TypeOf((*MockObjectStorage)(nil).PresignedURLFromBucket), ctx, bucket, key)
}

// Upload mocks base method.
func (m *MockObjectStorage) Upload(ctx context.Context, key string, reader io.Reader, size int64, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, key, reader, size, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockObjectStorageMockRecorder) Upload(ctx, key, reader, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockObjectStorage)(nil).Upload), ctx, key, reader, size, contentType)
}

// UploadToBucket mocks base method.
func (m *MockObjectStorage) UploadToBucket(ctx context.Context, bucket, key string, reader io.Reader, size int64, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadToBucket", ctx, bucket, key, reader, size, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadToBucket indicates an expected call of UploadToBucket.
func (mr *MockObjectStorageMockRecorder) UploadToBucket(ctx, bucket, key, reader, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadToBucket", reflect.TypeOf((*MockObjectStorage)(nil).UploadToBucket), ctx, bucket, key, reader, size, contentType)
}

// Ping mocks base method.
func (m *MockObjectStorage) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockObjectStorageMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockObjectStorage)(nil).Ping), ctx)
}
